student/student/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 resources :studs, only: [:show, :create, :update, :destroy, :index,:new]
 resources :groups,  only: [:show, :create, :update, :destroy, :index,:new] do
 	post 'groups/add_student' => 'groups#add_student' , :as => :add_student
 end
 resources :marks do
 	get 'marks/weighted_averg' => 'marks#weighted_averg' , :as => :weighted_averg
 end
 root "studs#index"
end



 #     resources :teams, only: [:show, :create, :update, :destroy, :index,:new] do
 #   post 'teams/addemployee' => 'teams#addemployee' , :as => :addemployee_team
 # end

student/student/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

student/student/app/models/group.rb
class Group < ApplicationRecord
	 has_and_belongs_to_many :studs
end

student/student/app/models/mark.rb
class Mark < ApplicationRecord
  belongs_to :stud
  belongs_to :subject
 
  def self.avg(marks)
   marks.each do |m|
     
	     	if m.subject_id == 1
	       	 @weigth_maths = m.marks * 0.40
	      elsif m.subject_id == 2
	      	 @weigth_physics = m.marks * 0.30
	      elsif m.subject_id == 3
	      	 @weigth_chemistry = m.marks * 0.20
	      else m.subject_id == 5
	      	 @weigth_english = m.marks * 0.10
	      end
    end
    avg = ( @weigth_maths.to_i + @weigth_physics.to_i + @weigth_chemistry.to_i + @weigth_english.to_i) / 4
  end
end

student/student/app/models/stud.rb
class Stud < ApplicationRecord
	 has_many :marks
	 has_and_belongs_to_many :groups
end

student/student/app/models/subject.rb
class Subject < ApplicationRecord
	has_many :marks
end

student/student/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

student/student/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

student/student/app/controllers/groups_controller.rb
class GroupsController < ApplicationController
	def index
		@groups = Group.all
	end

	def show
		@group = Group.find(params[:id])	
	end

	def new
		@group = Group.new
	end

	def create
		respond_to do |f|
			@group = Group.new(group_params)
			if @group.save
				f.html { redirect_to @group, notice: 'Group was successfully added' }
			else
				render 'new'
			end
		end
	end

	def add_student
		if params[:group_id]
			@group =Group.find(params[:group_id])
			@addstudent = Stud.find_by_id(params[:stud][:id])
			@group.studs << @addstudent
	    redirect_to :action => 'index'
	  end
	end

	private
	def group_params
		params.require(:group).permit(:name)
	end
end

student/student/app/controllers/marks_controller.rb
class MarksController < ApplicationController
	def index
		@marks = Mark.all
	end

	def show
		@mark = Mark.find(params[:id])
	end

	def new
		@mark = Mark.new
	end

	def create
		respond_to do |f|
			@mark = Mark.new(marks_params)
			if @mark.save
				f.html { redirect_to @mark, notice: 'Mark was successfully added' }
			else
				render 'new'
			end
		end
	end

	def weighted_averg
    @student = Stud.find_by(params[:stud_id])
    @marks = Mark.where(stud_id: @student.id)
    @avg = Mark.avg(@marks)
   end

	private
	def marks_params
		params.require(:mark).permit(:marks, :stud_id, :subject_id)
	end
end

student/student/app/controllers/studs_controller.rb
class StudsController < ApplicationController
	def index
		@students = Stud.all
	end

  def show
 		@student = Stud.find(params[:id])
  end

	def new
		@student = Stud.new
  end

  def create
     
    respond_to do |f|
    	@student = Stud.new(student_params)
   		if @student.save
    	 # f.html { redirect_to @student, notice: 'Student was successfully added' }
       @students = Stud.all
       f.js{ }
      else
    	 render "new"
    	end
    end
  end

  private
  def student_params
  	params.require(:stud).permit(:name, :email)
  end

end

     

student/student/app/helpers/application_helper.rb
module ApplicationHelper
end

student/student/app/helpers/groups_helper.rb
module GroupsHelper
end

student/student/app/helpers/marks_helper.rb
module MarksHelper
end

student/student/app/helpers/studs_helper.rb
module StudsHelper
end

student/student/app/views/groups/index.html.erb
<h1>List of Groups</h1>
<% if @groups.blank? %>
		<p>No groups</p>
<% else %>
		<p>Current groups</p>
		<ul id = "groups" >
			<%@groups.each do |g| %>
				<li><%= g.name %></li>
				<%= link_to 'Show', group_path(g.id)%> 
			<%end%>
		</ul>
<% end %>
<%= link_to 'Add new group', new_group_path %> 

student/student/app/views/groups/new.html.erb
<h1>Add Group</h1>

<%= form_for @group do |g|%>
	<div class = "filed">
		<%= g.label :name %></br>
		<%= g.text_field :name %> 
	</div>
	<div class = "action">
	 <%= g.submit %>
	</div>
<%end%>

<%= link_to 'Back', groups_path %> 

student/student/app/views/groups/show.html.erb
<h1><%= @group.name %></h1>
<p>Add student to group</p>
<%= form_tag group_add_student_path (@group.id) do %>
	<%= collection_select(:stud, :id, Stud.all, :id, :name,  :prompt => true)%>
	<%= submit_tag %>
<% end %>

student/student/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Student</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<% if notice %>
  		<p class="alert alert-success"><%= notice %></p>
		<% end %>
		<% if alert %>
  		<p class="alert alert-danger"><%= alert %></p>
		<% end %>
		<p class="navbar-text pull-right">
		<% if user_signed_in? %>
  		Logged in as <strong><%= current_user.email %></strong>.
  		<%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  		<%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
		<% else %>
  		<%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  		<%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
		<% end %>
		</p>
    <%= yield %>
  </body>
</html>

student/student/app/views/marks/new.html.erb
<h1>Add Marks</h1>
<%= form_for @mark do |m| %>
 <div class = "field">
 	<%= m.label :marks %>
 	<%= m.text_field :marks%>
 </div>
 <div class ="dropdown">
  <p>
  Student
 	<%= m.collection_select(:stud_id, Stud.all, :id, :name )%>
  </p>
  <p>
  Subject
 	<%= m.collection_select(:subject_id, Subject.all, :id, :name )%>
 	</p>
 </div>
 	<div class = "action">
	 <%= m.submit %>
	</div>
<%end%>

student/student/app/views/marks/show.html.erb
<p>mark</p>

student/student/app/views/marks/weighted_averg.html.erb
<h1>Weighted Average</h1>
<table style="width:25%" border="2px">
  <tr>
    <th>Name</th>
    <th>Weigthed Average</th> 
  </tr>
  <tr>
    <td><%= @student.name %></td>
    <td><%=  @avg %></td> 
  </tr>
</table>
<%= link_to 'Back', new_mark_path %>

student/student/app/views/studs/_display.html.erb
<p>
  <strong>Name:</strong>
  <%= @student.name %>
</p>
 
<p>
  <strong>Email Id:</strong>
  <%= @student.email %>
</p>

<p><%= link_to 'Back', studs_path %></p>

student/student/app/views/studs/_form.html.erb
<%= form_for @student,  html: { class: 'form-horizontal', :id=>"your_form_id" }, remote: true do |s| %>
	<div class="fields">
		<p>
			<%= s.label :name %><br>
			<%= s.text_field :name %>
		</p>
		<p>
			<%= s.label :email %><br>
			<%= s.text_field :email %>
	  </p>
	 </div>
	<div class="action">
		<%= s.submit %>
	</div>
<%end%>

student/student/app/views/studs/_list.html.erb
<table style="width:25%" border="2px">
  <tr>
    <th>Name</th>
    <th>Email</th> 
  </tr>
  <% @students.each do |s|%>
  <tr>
    <td><%= s.name %></td>
    <td><%= s.email %></td> 
   <td> <%= link_to 'Show',  stud_path(s.id) %> </td>
  </tr>
  <% end %>
</table>

student/student/app/views/studs/create.js.erb
// alert("haii");

// $("#your_form_id").html("<%= escape_javascript(render partial: 'display') %>");
$("#your_form_id").html("<%= escape_javascript(render partial: 'list') %>");

student/student/app/views/studs/index.html.erb
<h1>Students List</h1>

<table style="width:25%" border="2px">
  <tr>
    <th>Name</th>
    <th>Email</th> 
  </tr>
  <% @students.each do |s|%>
  <tr>
    <td><%= s.name %></td>
    <td><%= s.email %></td> 
   <td> <%= link_to 'Show',  stud_path(s.id) %> </td>
  </tr>
  <% end %>
</table>
<p>
 <%= link_to 'Create new student', new_stud_path %> </br>
 <%= link_to 'See Groups', groups_path %> </br>
 <%= link_to 'Add Marks', new_mark_path %> 
</p>

student/student/app/views/studs/new.html.erb
<h1>Add New Student</h1>
 <%= render 'form'%>

<p><%= link_to 'Back', studs_path %></p>

student/student/app/views/studs/show.html.erb
<h1>Student Details</h1>
<%= render 'display'%>
<%= link_to 'weigthed average', mark_weighted_averg_path(:mark_id)%>